Enabled cache

diff --git a/.github/workflows/check-gentx.yml b/.github/workflows/check-gentx.yml
--- a/.github/workflows/check-gentx.yml
+++ b/.github/workflows/check-gentx.yml
@@ -11,7 +11,7 @@ on:
       - main
       - genesis/athens3-reduced-steps
     paths:
-      - 'genesis_files/**'
+      - "genesis_files/**"
 
 env:
   # ZETACORED_BINARY: "https://zetachain-external-files.s3.amazonaws.com/binaries/athens3/latest/zetacored-ubuntu"
@@ -24,33 +24,28 @@ env:
 
 jobs:
   check-gentx:
-      runs-on: ["ubuntu-22.04"]
-      timeout-minutes: 15
-      steps:
-
+    runs-on: ["ubuntu-22.04"]
+    timeout-minutes: 10
+    steps:
       - uses: actions/checkout@v3
 
-      # - name: Restore Cache
-      #   uses: actions/cache@v2
-      #   with:
-      #     path: /usr/bin/zetacored
-      #     key: ${{ runner.os }}-zetacored-${{ hashFiles('zetacored') }}
+      - name: Restore Cached Binary
+        uses: actions/cache/restore@v3
+        id: restore-cache
+        with:
+          path: /usr/bin/zetacored
+          key: ${{ runner.os }}-zetacored-${{ hashFiles('zetacored') }}
 
       - name: Download Zetacored
-        # if: steps.restore-cache.outputs.cache-hit != 'true'
+        if: steps.restore-cache.outputs.cache-hit != 'true'
         run: |
+          echo "Downloading Latest Zetacored From $ZETACORED_BINARY"
           wget $ZETACORED_BINARY -O zetacored
-          mv zetacored /usr/bin/zetacored
+          sudo mv zetacored /usr/bin/zetacored
           sudo chmod +x /usr/bin/zetacored
           zetacored version
 
-      # - name: Install Binaries
-      #   run: |
-      #     mv zetacored ~/.local/bin/zetacored
-      #     sudo chmod +x /usr/bin/zetacored
-      #     zetacored version
-        
-      - name: Check GentX Is Valid
+      - name: Validate GentX and OS_INFO files
         run: |
           rm -rf ~/.zetacored/ || true
           zetacored init Zetanode --chain-id=$CHAINID
@@ -82,28 +77,29 @@ jobs:
             exit 1
           fi
 
-      - name: Start Chain For Testing
+      - name: Start Zetacored
         run: |
           zetacored start --trace \
           --minimum-gas-prices=0.0001azeta \
           --json-rpc.api eth,txpool,personal,net,debug,web3,miner \
-          --api.enable >> ~/.zetacored/zetacored.log # 2>&1  &
+          --api.enable >> ~/.zetacored/zetacored.log 2>&1  &
 
-          # sleep 15
-          # latest_block_height=$(curl --request GET -sL --url 'localhost:26657/status' --header 'Content-Type: application/json' | jq '.result.sync_info.latest_block_height|tonumber')
-          # echo "latest_block_height: $latest_block_height"
-          # if [ "$latest_block_height" -ge 3 ]; then
-          #     echo "SUCCESS"
-          #     echo "gentx and OS_INFO files are valid"
-          #     exit 0
-          # else
-          #   echo "FAILURE"
-          #     echo "gentx or OS_INFO files are inValid"
-          #     exit 1
-          # fi
+          sleep 6
+          latest_block_height=$(curl --request GET -sL --url 'localhost:26657/status' --header 'Content-Type: application/json' | jq '.result.sync_info.latest_block_height|tonumber')
 
-      # - name: Cache Binary
-      #   uses: actions/upload-artifact@v2
-      #   with:
-      #     name: ${{ runner.os }}-zetacored-${{ hashFiles('zetacored') }}
-      #     path: /usr/bin/zetacored
+          if [ "$latest_block_height" -ge 0 ]; then
+              echo "SUCCESS"
+              echo "zetacored started successfully"
+              exit 0
+          else
+            echo "FAILURE"
+            echo "zetacored failed to start"
+            exit 1
+          fi
+
+      - name: Save Binary To Cache
+        uses: actions/cache/save@v3
+        if: steps.restore-cache.outputs.cache-hit != 'true'
+        with:
+          path: /usr/bin/zetacored
+          key: ${{ runner.os }}-zetacored-${{ hashFiles('zetacored') }}
